### ISSUE TITLE
Missing illustration

### ISSUE THREAD

**Issue by shi-weili** [bluecadet/nab-wall-cms#33]
"\"Cousin Brucie\" Bruce Morrow"
"Gerry House"
"Dave Ramsey"
"Chuck Lorre"
"Delilah"
"Maria Elena Salinas"
"\"Wheel of Fortune\""
"Sylvester L. Weaver"
"Cathy Hughes"
"American Idol"
"Mike and Mike"
"Carsey Werner Company"
"“FOX NFL Sunday”"
"Elvis Duran"

**Comment by pingevt** [comment]
@shi-weili placeholders in place
